version = 0.1

[default.deploy.parameters]
stack_name = "saturn-excel-ingestion"
resolve_s3 = true
s3_prefix = "saturn-excel-ingestion"
region = "us-east-1"
profile = "saturn"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "us-east-1"
